"""add isdriver to user

Revision ID: d15f5123510f
Revises: 23a5eaef0cc6
Create Date: 2025-06-27 13:35:57.234654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15f5123510f'
down_revision = '23a5eaef0cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_driver', sa.Boolean(), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('is_driver')

    # ### end Alembic commands ###
